site_name: Yet Another Jira Wrapper

nav:
  - Home: index.md
  - Getting Started: getting-started/index.md
  - User Guide: user-guide/index.md
  - API Reference: 
    - API Reference: api-reference/index.md
    - Module yajaw.jira: api-reference/yajaw.jira.md
    - Module yajaw.configuration: api-reference/yajaw.configuration.md
    - Module yajaw.exceptions: api-reference/yajaw.exceptions.md
  - About:
    - About: about/index.md
    - Release Notes: about/release_notes.md
    - Contribution: about/contribution.md
    - License: about/license.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins: 
  - mkdocstrings

copyright: |
  &copy; 2024 <a href="https://github.com/rmrighes"  target="_blank" rel="noopener">Rafael Maestri Righes</a>