# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CD - Publish to TestPyPi and PyPi

on: 
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-to-testpypi:
    runs-on: ubuntu-latest
    name: Publish to TestPyPi
    environment: testpypi
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        hatch run pip install --upgrade pip
    - name: Build package with hatch
      run: hatch build
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    runs-on: ubuntu-latest
    name: Publish to PyPi
    environment: pypi
    needs: publish-to-testpypi
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch run pip install --upgrade pip
      - name: Build package with hatch
        run: hatch build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1